# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassificationResult": types.ClassificationResult,
    "stream_types.ClassificationResult": stream_types.ClassificationResult,

    "types.ClassifiedType": types.ClassifiedType,
    "stream_types.ClassifiedType": stream_types.ClassifiedType,

    "types.PiiMatch": types.PiiMatch,
    "stream_types.PiiMatch": stream_types.PiiMatch,


}