# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class ClassificationResult(BaseModel):
    classifications: typing.List["ItemClassification"]

class ItemClassification(BaseModel):
    name: typing.Optional[str] = None
    classification: typing.Optional[typing.Union[typing_extensions.Literal['public'], typing_extensions.Literal['private'], typing_extensions.Literal['confidential'], typing_extensions.Literal['highly-confidential']]] = None
    rationale: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class PayloadItemInput(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    samples: typing.Optional[typing.List[str]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
