# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassificationResult": types.ClassificationResult,
    "stream_types.ClassificationResult": stream_types.ClassificationResult,

    "types.ItemClassification": types.ItemClassification,
    "stream_types.ItemClassification": stream_types.ItemClassification,

    "types.PayloadItemInput": types.PayloadItemInput,
    "stream_types.PayloadItemInput": stream_types.PayloadItemInput,


}